services:
  wordpress:
    build: ./wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    env_file: 
      - ${SECRET_DIR}/nginx.env
      - ${SECRET_DIR}/wordpress.env
      - ${SECRET_DIR}/mariadb.env
    networks:
      - inception-network
    volumes:
      - wordpress-vol:/var/www/html
    depends_on:
      - mariadb
    restart: always
  
  mariadb:
    build: ./mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    env_file: 
      - ${SECRET_DIR}/mariadb.env
    networks:
      - inception-network
    volumes:
      - mariadb-vol:/var/lib/mysql
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    image: nginx
    restart: always
    env_file: 
      - ${SECRET_DIR}/nginx.env
    ports:
      - '8080:443'
    networks:
      - inception-network
    depends_on:
      - wordpress
    volumes:
      - wordpress-vol:/var/www/html
    restart: always

networks:
  inception-network:
    driver: bridge

volumes:
  wordpress-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_DIR:-/home/maiboyer/data}/wordpress
    name: "wordpress-volume"
  mariadb-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_DIR:-/home/maiboyer/data}/mariadb
    name: "mariadb-volume"

