services:
  wordpress:
    build: ./wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    env_file: 
      - ../.env
    networks:
      - inception-network
    volumes:
      - wordpress-vol:/var/www/html
    depends_on:
      - mariadb
  
  mariadb:
    build: ./mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    env_file: 
      - ../.env
    networks:
      - inception-network
    volumes:
      - mariadb-vol:/var/lib/mysql

  nginx:
    build: ./nginx
    container_name: nginx
    image: nginx
    restart: always
    env_file: 
      - ../.env
    ports:
      - '443:443'
    networks:
      - inception-network
    depends_on:
      - wordpress
      - site
      - adminer
      - netdata
    volumes:
      - wordpress-vol:/var/www/html

# BEGIN BONUS STUFF HERE

  redis:
    build: ./bonus/redis
    container_name: redis
    image: redis
    restart: always
    networks:
      - inception-network
    volumes:
      - wordpress-vol:/var/www/html
    depends_on:
      - wordpress 

  ftp:
    build: ./bonus/ftp
    container_name: ftp
    image: ftp
    restart: always
    env_file: 
      - ../.env
    networks:
      - inception-network
    volumes:
      - wordpress-vol:/var/www/html
    depends_on:
      - wordpress
    ports:
      # server listening port
      - '21:21'
      # required for ftp use. Idk why. probably because it allocate a port per active user ?
      - '21100-21110:21100-21110'

  adminer:
    build: ./bonus/adminer
    container_name: adminer
    image: adminer
    restart: always
    networks:
      - inception-network
    depends_on:
      - mariadb
  
  site:
    build: ./bonus/site/
    container_name: site
    image: site
    restart: always
    networks:
      - inception-network


  netdata:
    build: ./bonus/netdata/
    container_name: netdata
    image: netdata
    restart: always
    networks:
      - inception-network
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    volumes:
      - /:/host/root:ro,rslave
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/etc/localtime:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /var/log:/host/var/log:ro

# END BONUS STUFF HERE

networks:
  inception-network:
    driver: bridge

volumes:
  wordpress-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_DIR:-/home/${USER}/data}/wordpress
    name: "wordpress-volume"
  mariadb-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_DIR:-/home/${USER}/data}/mariadb
    name: "mariadb-volume"

