services:
  wordpress:
    build: ./wordpress
    container_name: wordpress
    image: wordpress
    restart: always
    env_file: 
      - ${SECRET_DIR}/nginx.env
      - ${SECRET_DIR}/wordpress.env
      - ${SECRET_DIR}/mariadb.env
    networks:
      - inception-network
    volumes:
      - wordpress-vol:/var/www/html
    depends_on:
      - mariadb
  
  mariadb:
    build: ./mariadb
    container_name: mariadb
    image: mariadb
    restart: always
    env_file: 
      - ${SECRET_DIR}/mariadb.env
    networks:
      - inception-network
    volumes:
      - mariadb-vol:/var/lib/mysql

  nginx:
    build: ./nginx
    container_name: nginx
    image: nginx
    restart: always
    env_file: 
      - ${SECRET_DIR}/nginx.env
    ports:
      - '443:443'
    networks:
      - inception-network
    depends_on:
      - wordpress
      - site
      - adminer
    volumes:
      - wordpress-vol:/var/www/html

  redis:
    build: ./bonus/redis
    container_name: redis
    image: redis
    restart: always
    networks:
      - inception-network
    volumes:
      - wordpress-vol:/var/www/html
    depends_on:
      - wordpress 

  ftp:
    build: ./bonus/ftp
    container_name: ftp
    image: ftp
    restart: always
    env_file: 
      - ${SECRET_DIR}/ftp.env
    networks:
      - inception-network
    volumes:
      - wordpress-vol:/var/www/html
    depends_on:
      - wordpress
    ports:
      # server listening port
      - '21:21'
      # required for ftp use. Idk why. probably because it allocate a port per active user ?
      - '21100-21110:21100-21110'

  adminer:
    build: ./bonus/adminer
    container_name: adminer
    image: adminer
    restart: always
    networks:
      - inception-network
    depends_on:
      - mariadb
  
  site:
    build: ./bonus/site/
    container_name: site
    image: site
    restart: always
    networks:
      - inception-network

networks:
  inception-network:
    driver: bridge

volumes:
  wordpress-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_DIR:-/home/maiboyer/data}/wordpress
    name: "wordpress-volume"
  mariadb-vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATA_DIR:-/home/maiboyer/data}/mariadb
    name: "mariadb-volume"

